import * as THREE from 'three';

/**
 * Encodes a THREE.BufferGeometry into standard Binary STL ArrayBuffer
 */
export function geometryToBinarySTL(geometry: THREE.BufferGeometry): ArrayBuffer {
  // Ensure we have non-indexed positions
  const nonIndexed = geometry.index ? geometry.toNonIndexed() : geometry;
  const pos = nonIndexed.getAttribute('position');
  const count = pos.count / 3;

  const bufferSize = 84 + count * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // 80-byte header
  const header = 'Binary STL Generated by Vibey Slicer';
  for (let i = 0; i < 80; i++) {
    view.setUint8(i, i < header.length ? header.charCodeAt(i) : 0);
  }

  // 4-byte triangle count
  view.setUint32(80, count, true);

  let offset = 84;
  const pA = new THREE.Vector3();
  const pB = new THREE.Vector3();
  const pC = new THREE.Vector3();
  const cb = new THREE.Vector3();
  const ab = new THREE.Vector3();

  for (let i = 0; i < count; i++) {
    pA.fromBufferAttribute(pos, i * 3);
    pB.fromBufferAttribute(pos, i * 3 + 1);
    pC.fromBufferAttribute(pos, i * 3 + 2);

    cb.subVectors(pC, pB);
    ab.subVectors(pA, pB);
    cb.cross(ab).normalize();

    // Normal
    view.setFloat32(offset, cb.x, true);
    view.setFloat32(offset + 4, cb.y, true);
    view.setFloat32(offset + 8, cb.z, true);
    offset += 12;

    // V1
    view.setFloat32(offset, pA.x, true);
    view.setFloat32(offset + 4, pA.y, true);
    view.setFloat32(offset + 8, pA.z, true);
    offset += 12;

    // V2
    view.setFloat32(offset, pB.x, true);
    view.setFloat32(offset + 4, pB.y, true);
    view.setFloat32(offset + 8, pB.z, true);
    offset += 12;

    // V3
    view.setFloat32(offset, pC.x, true);
    view.setFloat32(offset + 4, pC.y, true);
    view.setFloat32(offset + 8, pC.z, true);
    offset += 12;

    // Attribute byte count
    view.setUint16(offset, 0, true);
    offset += 2;
  }

  return buffer;
}

export function createCalibrationCubeSTL(): ArrayBuffer {
  // 20x20x20mm Cube
  const geom = new THREE.BoxGeometry(20, 20, 20);
  return geometryToBinarySTL(geom);
}

export function createHollowCylinderSTL(): ArrayBuffer {
  // Outer cylinder radius 12mm, height 18mm, with inner hole radius 6mm
  const shape = new THREE.Shape();
  shape.absarc(0, 0, 12, 0, Math.PI * 2, false);

  const holePath = new THREE.Path();
  holePath.absarc(0, 0, 6, 0, Math.PI * 2, true);
  shape.holes.push(holePath);

  const extrudeSettings = {
    steps: 1,
    depth: 18,
    bevelEnabled: false
  };

  const geom = new THREE.ExtrudeGeometry(shape, extrudeSettings);
  geom.center();
  return geometryToBinarySTL(geom);
}

export function createStepPyramidSTL(): ArrayBuffer {
  // 3-step pyramid: base 30x30, mid 20x20, top 10x10, height 18mm
  const group = new THREE.Group();

  const b1 = new THREE.Mesh(new THREE.BoxGeometry(28, 28, 6));
  b1.position.z = 3;
  group.add(b1);

  const b2 = new THREE.Mesh(new THREE.BoxGeometry(20, 20, 6));
  b2.position.z = 9;
  group.add(b2);

  const b3 = new THREE.Mesh(new THREE.BoxGeometry(12, 12, 6));
  b3.position.z = 15;
  group.add(b3);

  // Merge geometries
  const geometries: THREE.BufferGeometry[] = [];
  group.updateMatrixWorld(true);
  group.traverse((c) => {
    if (c instanceof THREE.Mesh) {
      const g = c.geometry.clone();
      g.applyMatrix4(c.matrixWorld);
      geometries.push(g);
    }
  });

  // Simple box concatenation
  const posList: number[] = [];
  geometries.forEach(g => {
    const p = g.getAttribute('position');
    for (let i = 0; i < p.count; i++) {
      posList.push(p.getX(i), p.getY(i), p.getZ(i));
    }
  });

  const merged = new THREE.BufferGeometry();
  merged.setAttribute('position', new THREE.Float32BufferAttribute(posList, 3));
  merged.computeVertexNormals();
  return geometryToBinarySTL(merged);
}

/**
 * Creates an Overhang & Cantilever Bridge Test Model (T-bracket with 90° ceiling and 60° overhang)
 */
export function createOverhangTestSTL(): ArrayBuffer {
  const group = new THREE.Group();

  // 1. Bed Base Plate: 32 x 20 x 4mm
  const base = new THREE.Mesh(new THREE.BoxGeometry(32, 20, 4));
  base.position.set(0, 0, 2);
  group.add(base);

  // 2. Vertical Column Pillar on Left: 10 x 20 x 22mm (reaching Z=24mm)
  const pillar = new THREE.Mesh(new THREE.BoxGeometry(10, 20, 20));
  pillar.position.set(-11, 0, 14);
  group.add(pillar);

  // 3. Horizontal Cantilever Arm Extending Right: 20 x 20 x 6mm (at Z=21mm, underside at Z=18mm)
  // Suspended 14mm above bed plate!
  const cantilever = new THREE.Mesh(new THREE.BoxGeometry(20, 20, 6));
  cantilever.position.set(4, 0, 21);
  group.add(cantilever);

  // 4. Overhang Sloped Ramp on Front (60° Overhang wedge test)
  // Using a tilted box
  const ramp = new THREE.Mesh(new THREE.BoxGeometry(8, 6, 12));
  ramp.rotation.x = Math.PI / 4; // 45 deg overhang
  ramp.position.set(4, -10, 11);
  group.add(ramp);

  // Merge geometries
  const geometries: THREE.BufferGeometry[] = [];
  group.updateMatrixWorld(true);
  group.traverse((c) => {
    if (c instanceof THREE.Mesh) {
      const g = c.geometry.clone();
      g.applyMatrix4(c.matrixWorld);
      geometries.push(g);
    }
  });

  const posList: number[] = [];
  geometries.forEach((g) => {
    const p = g.getAttribute('position');
    for (let i = 0; i < p.count; i++) {
      posList.push(p.getX(i), p.getY(i), p.getZ(i));
    }
  });

  const merged = new THREE.BufferGeometry();
  merged.setAttribute('position', new THREE.Float32BufferAttribute(posList, 3));
  merged.computeVertexNormals();
  return geometryToBinarySTL(merged);
}

